AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

inherit_gem:
  rubocop-ronin: rubocop.yml

#
# ronin-dns-proxy specific exceptions
#
Style/CaseEquality:
  Exclude:
    - 'lib/ronin/dns/proxy/rule.rb'
